### ISSUE TITLE
Create User (and enforce permissions to db)

### ISSUE THREAD

**Issue by hongkongkiwi** [square/password-rotation-lambda#5]
Thanks for building this, it's exactly what I'm looking for.

I would like the feature to create the MySQL user as well (and ideally set/enforce permissions).

That way, I can just create the user definitions in secrets manager and some random password and it will rotate when the lambda is called (and create if necessary).

**Comment by daniel-nichter** [comment]
Hi. That's an interesting idea. I'm not sure this package can support it without some significant changes, but first let me see if I understand the idea. First, you'd have a secret like:
```json
{
  "username": "newUser",
  "password": "newPassToBeRotated",
}
```
Then, the PRL (password rotation lambda) would connect to MySQL as some pre-existing root user (i.e. a user who has `WITH GRANT OPTION`). Lastly, as that root user, it'd `CREATE USER IF EXISTS newUser` and rotate its password.

Is that the process?

**Comment by daniel-nichter** [comment]
Let me know how you see this process working. Will close this issue until then.

**Comment by estahn** [comment]
@daniel-nichter I found your article "MySQL Password Rotation with AWS Secrets Manager and Lambda" and this repository interesting.  You describe the concept of "Default Provisioning Password" in your article. Which I believe is exactly what @hongkongkiwi describes.

Essentially a [controller](https://kubernetes.io/docs/concepts/architecture/controller/) that watches the secrets and makes changes based on emitted events. As for user creation you probably can use the the RDS root secrets or another configured secret with the necessary permissions.

I wonder how do you deal with DPP right now? I was under the impression this tool would do that.
